language: go

go:
    - 1.7.x


sudo: required

before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
    - sudo unzip protoc-3.2.0-linux-x86_64.zip -d /usr/local

install: make install