version: 2.1

executors:
  exec:
    docker:
      - image: golang:latest 

jobs:
  build:
    executor: exec
    steps:
      - checkout
      - run: |
          apt update -y && apt install -y xz-utils
          GOOS="darwin" GOARCH="amd64" go install -i std
          ./pleasew build -p 
  github-release:
    executor: exec
    steps:
      - checkout
      - run:
          name: "Publish Release on Github"
          command: |
            apt update -y && apt install -y xz-utils/
            GOOS="darwin" GOARCH="amd64" go install -i std
            ./pleasew build -p
            go get github.com/tcnksm/ghr
            mkdir artifacts
            cp $(./pleasew query output //:protoc-gen-persist-linux-amd64) artifacts/protoc-gen-persist-${CIRCLE_TAG}-linux-amd64.tar.gz
            cp $(./pleasew query output //:protoc-gen-persist-darwin-amd64) artifacts/protoc-gen-persist-${CIRCLE_TAG}-darwin-amd64.tar.gz
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace  ${VERSION} ./artifacts/ 

workflows:
  version: 2.1
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/ 
